{
    "##": "Generated by JReleaser on every release. Edit src/jreleaser/distributions/stealth/scoop/manifest.json.tpl in the stealth repo instead.",
    "version": "{{projectVersion}}",
    "description": "{{projectDescription}}",
    "homepage": "{{projectLinkHomepage}}",
    "license": "{{projectLicense}}",
    "url": "{{distributionUrl}}",
    "hash": "sha256:{{distributionChecksumSha256}}",
    "extract_dir": "{{distributionArtifactRootEntryName}}",
    "bin": "bin\\{{distributionExecutableWindows}}",
    "suggest": {
        "Java 21": [
            "java/temurin21-jre",
            "java/temurin21-jdk"
        ]
    }
}
